import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from './Components/Banner'
import Card from './Components/Card'
import Navbar from './Components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NetFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
       username={"arefin@gmail.com"}
      />
      <Banner
       title="Clifford the red dog"
       subTitle="a very cute dog"
       imgUrl="/static/clifford.jpg"
      />
      <Card
        imgUrl ="/static/clifford.jpg"
        size="large"
      />
      <Card
      />
      <Card
        imgUrl ="/static/clifford.jpg"
        size="small"
      />
    </div>
  )
}
